### ISSUE TITLE
RiqTam rompio main

### ISSUE THREAD

**Issue by abdielreyes** [RiqTam/Calculadora-verde#4]
RiqTam rompio mainRiqTam rompio mainRiqTam rompio mainRiqTam rompio mainRiqTam rompio mainRiqTam rompio mainRiqTam rompio mainRiqTam rompio mainRiqTam rompio mainRiqTam rompio mainRiqTam rompio mainRiqTam rompio mainRiqTam rompio mainRiqTam rompio mainRiqTam rompio mainRiqTam rompio mainRiqTam rompio mainRiqTam rompio mainRiqTam rompio mainRiqTam rompio mainRiqTam rompio mainRiqTam rompio mainRiqTam rompio mainRiqTam rompio mainRiqTam rompio mainRiqTam rompio mainRiqTam rompio mainRiqTam rompio mainRiqTam rompio mainRiqTam rompio mainRiqTam rompio mainRiqTam rompio mainRiqTam rompio mainRiqTam rompio mainRiqTam rompio mainRiqTam rompio mainRiqTam rompio mainRiqTam rompio mainRiqTam rompio mainRiqTam rompio mainRiqTam rompio mainRiqTam rompio mainRiqTam rompio mainRiqTam rompio mainRiqTam rompio mainRiqTam rompio mainRiqTam rompio mainRiqTam rompio mainRiqTam rompio mainRiqTam rompio main

**Comment by abdielreyes** [comment]
efectivamente
pero, rompio su main

**Comment by abdielreyes** [comment]
asi que es en su maquina

**Comment by abdielreyes** [comment]
nopuedeser valio

**Comment by RiqTam** [comment]
revivió banda, se cancela la emergencia
